### ISSUE TITLE
https port not work

### ISSUE THREAD

**Issue by rickywu** [extremeshok/docker-xmysql-https-auth#1]
Here is my docker-compose.yml

```
version: "2"

services:
  xshokxmysqlhttps:
    image: extremeshok/xmysql-https-auth:latest
    container_name: xmysql
    volumes:
      - ./certs:/certs/
    environment:
      - TZ=Asia/Shanghai
      - SQL_HOST=172.18.204.x
      - SQL_PORT=3306
      - SQL_DATABASE=report
      - SQL_USERNAME=root
      - SQL_PASSWORD=xxx
      - API_PREFIX=/
      #- API_FILTERTABLES=users,admins
      - API_IGNORETABLES=backends,stats,sessions
      - API_KEY=key
      #- API_ALLOW_IP=192.1.0.0/24,10.10.10.10
      #- API_HTTP_AUTH=username:{PLAIN}password
# used for server name, ssl cert
      - API_HOSTNAME=domain.net
    restart: always
    ports:
      - 3443:443
```

the container log

```
[services.d] starting services
#### Nginx SSL requirements ####
==== Generating 4096 dhparam ====
Generating DH parameters, 4096 bit long safe prime, generator 2
This is going to take a long time
[services.d] done.
mysqld is alive
Starting....



          Generating REST APIs at the speed of your thought..

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

          Database              :    report
          Number of Tables      :    19

          REST APIs Generated   :    366

          Xmysql took           :    0.2 seconds
          API's base URL        :    localhost:3000

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

```
I added user xs and chown -R xs:xs of xmysql folder, but the logs shows
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied

If I comment     user: "1006" this line, run as root user:
```
#### Nginx SSL requirements ####
==== Detected: /certs: cert,privkey ====
#### Generating Nginx API config ####
nginx: [emerg] PEM_read_bio_DHparams("/certs/dhparam.pem") failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: DH PARAMETERS)
```

But 3000 port on http works well
